/**
 * Emit token artifacts for downstream consumers of the design language:
 * values that consumer code must hold in code, not only via CSS custom
 * properties (media queries cannot read CSS vars) and compile-time
 * fragments the component build consumes in types and SCSS (a SCSS
 * `@each` cannot reflect a CSS-var family, so the key list itself is
 * emitted). Consumer projects declare the emission DIRECTORY in
 * colox.theme.build.json:
 *
 *   "runtime": { "type": "ts", "output": "./src/tokens" }
 *
 * File names inside that directory are decided by the builder (token
 * fragments are library default behavior — consumers never name the
 * files): breakpoints.ts today, more files as the language grows.
 *
 * Artifacts today:
 * - breakpoints.ts     responsive contract from base.tokens.json
 *                      (defaultBreakpoints for the ColoxTheme runtime)
 *                      -> written into the declared runtime `output`
 * - spacing.ts         the spacing scale key list + key union type
 *                      (single-sources the component variants layer)
 *                      -> written into the declared runtime `output`
 * - variables.scss     the theme SCSS surface: the same key lists for
 *                      component SCSS @each loops, consumed as
 *                      `@use '@colox/theme/variables'` and exposed by
 *                      the package exports `sass` condition
 *                      -> written next to the css suite (outDir)
 * The `type` field reserves the artifact-format slot for future kinds.
 *
 * Paths come from env (set by scripts/build.mjs):
 * - COLox_TOKENS_DIR  token workspace to read (base/size.tokens.json)
 * - COLox_RUNTIME_OUT output directory for runtime TS code (absolute)
 * - COLox_CSS_OUT     css suite directory for the SCSS surface (absolute)
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const tokensDir = process.env.COLox_TOKENS_DIR;
const outDir = process.env.COLox_RUNTIME_OUT;

if (!outDir) {
  console.error('emit-runtime: COLox_RUNTIME_OUT is required (set by scripts/build.mjs)');
  process.exit(1);
}

async function readTokenFile(file) {
  try {
    return JSON.parse(await readFile(path.join(tokensDir, file), 'utf8'));
  } catch (err) {
    console.error(`emit-runtime: cannot read ${path.join(tokensDir, file)}: ${err.message}`);
    process.exit(1);
  }
}

// Responsive contract: the runtime's default breakpoints.
const base = await readTokenFile('base.tokens.json');
const breakpoints = base.colox?.breakpoint ?? {};
if (Object.keys(breakpoints).length === 0) {
  console.error('emit-runtime: no breakpoints found in base.tokens.json');
  process.exit(1);
}

// Spacing scale keys: the design language's spacing group (already
// cleaned by figma-to-tokens: `_` -> `-`, so keys are class-name safe).
const size = await readTokenFile('size.tokens.json');
const spacing = size.colox?.spacing ?? {};
const spacingKeys = Object.keys(spacing);
if (spacingKeys.length === 0) {
  console.error('emit-runtime: no spacing keys found in size.tokens.json');
  process.exit(1);
}

const kebab = (s) => s.replaceAll('_', '-');

const generatedHeader = (source) =>
  [
    '// Generated by emit-runtime.mjs from the design-language token workspace',
    `// (${source}). Do not edit by hand.`,
  ].join('\n');

// One fragment per token group; file names are builder-owned API,
// extend this list as new values appear.
const artifacts = [
  {
    file: 'breakpoints.ts',
    render: () =>
      [
        generatedHeader('base.tokens.json'),
        '// Default contract breakpoints for the responsive runtime',
        '// (ColoxThemeContext defaults + head bootstrap script +',
        '// matchMedia observer).',
        'export const defaultBreakpoints = {',
        ...Object.entries(breakpoints).map(
          ([name, token]) => `  ${kebab(name)}: '${token.$value}',`,
        ),
        '} as const;',
      ].join('\n'),
  },
  {
    file: 'spacing.ts',
    render: () =>
      [
        generatedHeader('size.tokens.json'),
        '// Spacing scale keys, single-sourced: the component variants',
        '// layer builds its gutter/gap class maps from this list, so',
        '// design-language edits to the scale reach components without',
        '// a component-side re-keying.',
        'export const spacingKeys = [',
        ...spacingKeys.map((key) => `  '${key}',`),
        '] as const;',
        '',
        'export type SpacingKey = (typeof spacingKeys)[number];',
      ].join('\n'),
  },
  {
    file: 'variables.scss',
    dir: 'css',
    render: () =>
      [
        generatedHeader('size.tokens.json'),
        '// The theme SCSS surface for the design language. Consume it as',
        "// `@use '@colox/theme/variables' as tokens;` — component SCSS",
        '// reads the emitted key lists (spacing today; further fragment',
        '// blocks land in this file as the language grows).',
        '$colox-spacing-keys: (',
        ...spacingKeys.map((key) => `  '${key}',`),
        ');',
      ].join('\n'),
  },
];

const cssOut = process.env.COLox_CSS_OUT;

for (const artifact of artifacts) {
  const dir = artifact.dir === 'css' ? cssOut : outDir;
  if (!dir) {
    console.error(`emit-runtime: no output directory for ${artifact.file} (COLox_CSS_OUT missing)`);
    process.exit(1);
  }
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, artifact.file), artifact.render() + '\n');
  console.log(`[ok] token artifacts -> ${path.join(dir, artifact.file)}`);
}
