/**
 * Emit runtime token artifacts: design-language values the runtime must
 * consume in JS, not via CSS custom properties (media queries cannot
 * read CSS vars). Consumer projects declare the emission DIRECTORY in
 * colox.theme.build.json:
 *
 *   "runtime": { "type": "ts", "output": "./src/tokens" }
 *
 * File names inside that directory are decided by the builder (runtime
 * variables are library default behavior — consumers never name the
 * files): breakpoints.ts today, more files as the runtime grows.
 *
 * Today the fragment is the responsive contract breakpoints from the
 * token workspace's base.tokens.json (defaultBreakpoints for the
 * ColoxTheme runtime). Future runtime-facing tokens append new
 * artifacts to `artifacts` — `type` reserves the format slot.
 *
 * Paths come from env (set by scripts/build.mjs):
 * - COLox_TOKENS_DIR  token workspace to read (base.tokens.json)
 * - COLox_RUNTIME_OUT output directory (absolute)
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const tokensDir = process.env.COLox_TOKENS_DIR;
const outDir = process.env.COLox_RUNTIME_OUT;

if (!outDir) {
  console.error('emit-runtime: COLox_RUNTIME_OUT is required (set by scripts/build.mjs)');
  process.exit(1);
}

let base;
try {
  base = JSON.parse(await readFile(path.join(tokensDir, 'base.tokens.json'), 'utf8'));
} catch (err) {
  console.error(
    `emit-runtime: cannot read ${path.join(tokensDir, 'base.tokens.json')}: ${err.message}`,
  );
  process.exit(1);
}

const breakpoints = base.colox?.breakpoint ?? {};
if (Object.keys(breakpoints).length === 0) {
  console.error('emit-runtime: no breakpoints found in base.tokens.json');
  process.exit(1);
}

const kebab = (s) => s.replaceAll('_', '-');

// One fragment per runtime-consuming token group; file names are
// builder-owned API, extend this list as new runtime values appear.
const artifacts = [
  {
    file: 'breakpoints.ts',
    render: () =>
      [
        '// Generated by emit-runtime.mjs from the design-language token workspace',
        '// (base.tokens.json). Default contract breakpoints for the responsive',
        '// runtime (ColoxThemeContext defaults + head bootstrap script +',
        '// matchMedia observer). Do not edit by hand.',
        'export const defaultBreakpoints = {',
        ...Object.entries(breakpoints).map(
          ([name, token]) => `  ${kebab(name)}: '${token.$value}',`,
        ),
        '} as const;',
      ].join('\n'),
  },
];

await mkdir(outDir, { recursive: true });
for (const artifact of artifacts) {
  await writeFile(path.join(outDir, artifact.file), artifact.render() + '\n');
  console.log(`[ok] runtime tokens -> ${path.join(outDir, artifact.file)}`);
}
