/**
 * Emit runtime token artifacts: design-language values the runtime must
 * consume in JS, not via CSS custom properties (media queries cannot
 * read CSS vars). Consumer projects declare the emission target in
 * colox.theme.build.json:
 *
 *   "runtime": { "type": "ts", "output": "./src/tokens/runtime.ts" }
 *
 * Today this emits the responsive contract breakpoints from the token
 * workspace's base.tokens.json (defaultBreakpoints for the ColoxTheme
 * runtime). Future runtime-facing tokens extend this file's sections —
 * `type` reserves the format slot.
 *
 * Paths come from env (set by scripts/build.mjs):
 * - COLox_TOKENS_DIR  token workspace to read (base.tokens.json)
 * - COLox_RUNTIME_OUT absolute output file path
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const builderRoot = fileURLToPath(new URL('../', import.meta.url));
const tokensDir = process.env.COLox_TOKENS_DIR ?? path.join(builderRoot, 'src/styles/tokens');
const outFile = process.env.COLox_RUNTIME_OUT ?? path.join(builderRoot, 'dist/runtime-tokens.ts');

let base;
try {
  base = JSON.parse(await readFile(path.join(tokensDir, 'base.tokens.json'), 'utf8'));
} catch (err) {
  console.error(
    `emit-runtime: cannot read ${path.join(tokensDir, 'base.tokens.json')}: ${err.message}`,
  );
  process.exit(1);
}

const breakpoints = base.colox?.breakpoint ?? {};
if (Object.keys(breakpoints).length === 0) {
  console.error('emit-runtime: no breakpoints found in base.tokens.json');
  process.exit(1);
}

const kebab = (s) => s.replaceAll('_', '-');
const ts = [
  '// Generated by emit-runtime.mjs from the design-language token workspace',
  '// (base.tokens.json). Default contract breakpoints for the responsive',
  '// runtime (ColoxThemeContext defaults + head bootstrap script +',
  '// matchMedia observer). Do not edit by hand.',
  'export const defaultBreakpoints = {',
  ...Object.entries(breakpoints).map(([name, token]) => `  ${kebab(name)}: '${token.$value}',`),
  '} as const;',
].join('\n');

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, ts + '\n');
console.log(`[ok] runtime tokens -> ${outFile}`);
